#!/bin/bash
# bash is required because we need bash's printf to guarantee a cross-platform
# timestamp format.

set -e
set -x

if [ -e ~/.android/bashrc-ant-build ]; then
    . ~/.android/bashrc-ant-build
elif [ -z $ANDROID_HOME ]; then
    echo "ANDROID_HOME must be set!"
    exit
fi

projectroot=`pwd`

# standardize timezone to reduce build differences
export TZ=UTC
# run the clock at 5% speed, ant requires a moving clock
TIMESTAMP=`printf '@%(%Y-%m-%d %H:%M:%S)T x0.05' \
    $(git log -n1 --format=format:%at)`

git reset --hard
git clean -fdx

./setup-ant
cd cachewordlib

if [ -e ~/.android/ant.properties ]; then
    cp ~/.android/ant.properties .
    faketime -f "$TIMESTAMP" ant release
else
    echo "skipping release ant.properties, making debug build"
    faketime -f "$TIMESTAMP" ant debug
fi
