#!/bin/sh

set -e
set -x

if [ -z $ANDROID_HOME ]; then
    if [ -e ~/.android/bashrc ]; then
        . ~/.android/bashrc
    else
        echo "ANDROID_HOME must be set!"
        exit
    fi
fi

$ANDROID_HOME/tools/android update lib-project --path cachewordlib
$ANDROID_HOME/tools/android update lib-project --path cachewordhelpers
$ANDROID_HOME/tools/android update test-project --path cachewordtest --main ../cachewordlib


# fetch target from project.properties
eval `grep '^target=' sample/project.properties`
$ANDROID_HOME/tools/android update project --path sample --subprojects --target $target
